### ISSUE TITLE
missing glyphs: 2

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/rubik#1]
These updated in new src file.  Corrected unicode and added outline.

![Rubik 2019-10-11 at 6 45 42 PM](https://user-images.githubusercontent.com/6576107/66689172-cef54080-ec57-11e9-8e67-ac9c80779967.png)
![Rubik 2019-10-11 at 6 45 51 PM](https://user-images.githubusercontent.com/6576107/66689173-cef54080-ec57-11e9-82cc-1fecdae68bec.png)
![Rubik2019-10-11 at 6 46 52 PM](https://user-images.githubusercontent.com/6576107/66689174-cef54080-ec57-11e9-97bf-d9a04c0dc8cc.png)

**Comment by cjdunn** [comment]
This is resolved already
