### ISSUE TITLE
Spacing issue in feature variation for /finalpedagesh-hb.black /pedagesh-hb.black 

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/rubik#13]
We found `finalpedagesh-hb.black` and `pedagesh-hb.black` glyphs in Rubik, and decided to add a designspace rule to implement them from 700 and above. This change is committed to the `add-fea-var-2` branch.

The spacing in the sources looks fine, but some spacing weirdness happens happens when I type `HףּפּH` in Font Goggles. When the substitution happens, the spacing collapses. This persists even when I disable `kern`, `mark`, and `mkmk`. 

Below 700:

<img width="1240" alt="Screen Shot 2020-06-17 at 4 07 04 PM" src="https://user-images.githubusercontent.com/6578861/84945564-69dece00-b0b5-11ea-8b6a-9a72afb0b743.png">

700 and above:

<img width="1240" alt="Screen Shot 2020-06-17 at 4 07 09 PM" src="https://user-images.githubusercontent.com/6578861/84945598-7400cc80-b0b5-11ea-9b9b-6ca32218fa8d.png">

With OT positioning disabled:

<img width="1240" alt="Screen Shot 2020-06-17 at 4 09 03 PM" src="https://user-images.githubusercontent.com/6578861/84945613-795e1700-b0b5-11ea-8e5e-7208d1b468a1.png">

**Comment by moyogo** [comment]
There’s an extra `_center` anchor in `finalpedagesh-hb.black` that shouldn’t be there.
I think the other anchors in `finalpedagesh-hb.black` can be removed as well. `finalpedagesh-hb` doesn’t have any.
Glyphs.app would propagate the anchors from the base glyphs to those composite glyphs. Fontmake can do this as well with the ufo2ft propagateAnchors lib key.

@djrrb I’ve pushed commits for these in the `fix-finalpedagesh` branch.

**Comment by djrrb** [comment]
Amazing! Thank you so much.
