### ISSUE TITLE
Build: error 'buildStatTabe'

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/rubik#19]
_from fontTools.otlLib.builder import buildStatTable
ImportError: cannot import name 'buildStatTable' from 'fontTools.otlLib.builder' (/Users/pichotta/code/GoogleFonts/venv/lib/python3.7/site-packages/fontTools/otlLib/builder.py)_

**Comment by djrrb** [comment]
Hmmm @pichotta I can’t duplicate this...the build runs without issue on my end. 

It looks like it is referencing a function that should exist in the latest fontTools: https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/otlLib/builder.py#L2349 

Did you recently update gftools but not fontmake or fontTools, or something like that?

**Comment by pichotta** [comment]
I did recently update to the latest GF tools which had a fix to the MetaScript and a better STAT table.

**Comment by pichotta** [comment]
resolved by
pip install fontTools -U
pip install fontmake -U
