### ISSUE TITLE
Mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [TypeNetwork/rubik#21]
The horizontal bar of + − ÷ should be the same, and aligned vertically (in the middle) with × =.
<img width="993" alt="Rubik" src="https://user-images.githubusercontent.com/13808824/91024356-2003ee00-e5f8-11ea-9543-cf0dc4409c81.png">

**Comment by thlinard** [comment]
More complete specimen (1×<>+÷−¬=≠±≤≥3):
<img width="1736" alt="Rubik" src="https://user-images.githubusercontent.com/13808824/91159174-fb774700-e6c7-11ea-95ed-6e91bbfad21d.png">

**Comment by pichotta** [comment]
See https://github.com/googlefonts/rubik/issues/30
