### ISSUE TITLE
Dent in "a"

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/rubik#22]
We've had reports that the "a" has a dent.

<img width="497" alt="Screenshot 2020-08-24 at 15 03 50" src="https://user-images.githubusercontent.com/7525512/91053651-0922c300-e61b-11ea-8ef0-24be8c77d1b0.png">

cc @davelab6

**Comment by pichotta** [comment]
Redistributed points and structure to aid in better interpolation
