### ISSUE TITLE
Bracket layers triggering too early

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/rubik#3]
The Medium weight on Google Fonts has a euro which is constructed with two bars.

<img width="82" alt="Screenshot 2019-11-04 at 14 59 41" src="https://user-images.githubusercontent.com/7525512/68130729-c1a83a80-ff13-11e9-8b29-beff0dfa8457.png">

The version in this repo has just one.

<img width="180" alt="Screenshot 2019-11-04 at 15 00 09" src="https://user-images.githubusercontent.com/7525512/68130758-d1c01a00-ff13-11e9-885e-505620e4db7c.png">

This also seems to be happening for the yen and sheckel.

**Comment by cjdunn** [comment]
Fixed with this PR:
https://github.com/TypeNetwork/rubik/pull/6
