### ISSUE TITLE
Missing Glyphs?

### ISSUE THREAD

**Issue by cjdunn** [TypeNetwork/rubik#5]
@m4rc1e you reported via email:
- 2 missing glyphs as previously reported.

I want to confirm which glyphs these are.

 In the report I see: 
–uniFB43
It looks like this glyphs is in the sources (named:finalpedagesh-hb) but the unicode wasn't set, so I've set that now. 

–uni05B8
I don't see this glyph name or another glyph with this unicode in the google .glyphs sources or OTF/TTF from this repo: https://github.com/googlefonts/rubik
Is there a different source I should be looking at? Please advise, thanks. 

**PS the other issue for missing glyphs: https://github.com/TypeNetwork/rubik/issues/1
 lists that /qamatsqatan-hb (uni 05C7) was added but this is different from uni 05B8, so this appears to be a new issue and not a duplicate of the previously reported one.

**Comment by m4rc1e** [comment]
You're looking at the correct source. Just make sure that uniFB43 and uni05B8 are included and you're good.

**Comment by cjdunn** [comment]
Fixed with this PR: 
https://github.com/TypeNetwork/rubik/pull/6
