### ISSUE TITLE
f + accented character kerns

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/rubik#9]
f is colliding with iacute etc

![rubik_kern](https://user-images.githubusercontent.com/7525512/72251213-55be0e80-35f5-11ea-94ce-d0c8b5ac2fd1.gif)

**Comment by m4rc1e** [comment]
Line lengths of Roman fonts also differ quite a lot, when compared against the GF version.

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/72251920-6c189a00-35f6-11ea-8808-a3c34e18b102.gif)

"WA", "wa" feel too loose. I'd check if the kerns are compiling correctly. We may not be serving the newest version on GF so the kerning may be outdated.

**Comment by pichotta** [comment]
Light UFO shows kerning.  Looking further.

![Light UFO kerns WA](https://user-images.githubusercontent.com/6576107/77708048-597af380-6f9d-11ea-8de5-175d14fc37b0.png)

![Light UFO kern f igrave](https://user-images.githubusercontent.com/6576107/77708055-5d0e7a80-6f9d-11ea-8fd4-ec0f376d9972.png)

**Comment by pichotta** [comment]
A cracked Regular TTF shows this kerning.

![Reg UFO kerns WA](https://user-images.githubusercontent.com/6576107/77708078-71527780-6f9d-11ea-9c8f-acf0f891d29c.png)

![Reg UFO kern f igrave](https://user-images.githubusercontent.com/6576107/77708085-74e5fe80-6f9d-11ea-9f2f-cc5a779e19c9.png)

**Comment by pichotta** [comment]
The initial comment about /f colliding with /iacute.
It looks like what is happening is that /longs is colliding with /igrave.
The before and after TTFs when cracked do show kerning for this combination.

Before
![Reg Before](https://user-images.githubusercontent.com/6576107/77709153-88df2f80-6fa0-11ea-8190-52b6e5850d4b.png)

After
![Reg After](https://user-images.githubusercontent.com/6576107/77709162-92689780-6fa0-11ea-857e-65f82b20bd14.png)

**Comment by pichotta** [comment]
Checking the new Regular .ttf in InDn.  Kern values are present.

![InDn WA after TTF after](https://user-images.githubusercontent.com/6576107/77710045-5f73d300-6fa3-11ea-8b3f-392785bec8a6.png)

![InDn longs igrave TTF after](https://user-images.githubusercontent.com/6576107/77710052-626ec380-6fa3-11ea-9737-44d13a05ab5f.png)

**Comment by pichotta** [comment]
@m4rc1e   see today's previous comments above.

I get different report result when this command is used on the TTF vs. report.sh on the VF. 
What would be the next best test?

_gftools qa -f ttf/Rubik-Regular.ttf -gfb --diffenator --fontbakery_

vs.

this in the report.sh

_#!/bin/sh
set -e

gftools qa -f ../fonts/vf/Rubik[wght].ttf  -gfb --fontbakery --diffenator -o ../fonts/vf/out_roman

gftools qa -f ../fonts/vf/Rubik-Italic[wght].ttf  -gfb --fontbakery --diffenator -o ../fonts/vf/out_italic_

![TTF diff result1 ](https://user-images.githubusercontent.com/6576107/77710805-66034a00-6fa5-11ea-8d32-7272eaf673d4.png)

![TTF diff result2](https://user-images.githubusercontent.com/6576107/77710811-6996d100-6fa5-11ea-9937-2053102a5fc9.png)


![crack  wght ttf in RF](https://user-images.githubusercontent.com/6576107/77711208-bc24bd00-6fa6-11ea-9e16-b5b7f54d9b88.png)

**Comment by pichotta** [comment]
Troubleshooting list:

• use fontmake directly on the designspace (no build script postprocessing)
• ufo2glyphs and generating from Glyphs
• clearing UFO libs
• creating a new designspace (derived from the Italic, which works)
•  each font contains a GPOS table and a kern feature if I look in TTX, but no kerning visible in FontGoggles or elsewhere. There is kerning in the font
• language systems look fine
• features look fine
• lookups look fine
• groups list is the same
• not an issue with designspace
• fix anchors some glyphs had _bottom vs. _underscore bottom and two anchors on top of one another.

**Comment by djrrb** [comment]
@m4rc1e sorry for not following up on this sooner.

As you can see, the sources in the master branch will build instance fonts with kerning, but a variable font without kerning.

In the `hack-kerning` branch, I have put the Black Italic kerning in the Black. Now the variable font seems to work with kerning as expected.

Would love any suggestions about why you think this might be.

**Comment by djrrb** [comment]
Back on this...I seem to have come up with a solution that gets us a Roman Variable Font with more-or-less functioning kerning. By rearranging the groups, the kerning pair counts double but the visual results are quite close. This is demonstrated in the `flatten-and-compress-2` branch.

The process:
1) ufo2glyphs
2) Run [this script](https://github.com/justanotherfoundry/freemix-glyphsapp/blob/master/Expand%20Kerning.py) on all masters
3) Use Glyph’s built-in "Compress Kerning" 
4) glyphs2ufo

Running the results through diffenator doesn’t show many significant differences across the weights. These don’t seem to be regressions, though, and seem to be within an acceptable tolerance. 

![kerns_missing](https://user-images.githubusercontent.com/6578861/83272632-6385c200-a199-11ea-9e0c-4f90ae6b65db.gif)
![kerns_modified](https://user-images.githubusercontent.com/6578861/83272637-641e5880-a199-11ea-9b76-1c3cfe2b292c.gif)
![kerns_new](https://user-images.githubusercontent.com/6578861/83272641-641e5880-a199-11ea-90bf-652f9fce0c56.gif)
